#数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/customer?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true
    username: root
    password: 12345678
    max-idle: 10
    max-wait: 10000
    min-idle: 10
    initial-size: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
  application:
    name: cust-management
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8083

logging:
  root:
    leavel: debug

dubbo:
  protocol:
    name: dubbo
    port: 12345
  registry:
    protocol: zookeeper
    address: 127.0.0.1
    port: 2182